# Paths
csv_input_path: "../../CorpusFiles/HelperFiles/all_responses_cleaned.csv"
output_dir: "../Judgments/LLM/LLM-Judgments-NEW.csv"

# Generation parameters
max_input_length: 300
max_new_tokens: 50
min_new_tokens: 1

# Environment vars
pytorch_cuda_alloc_conf: "expandable_segments:True"